name: A workflow for my Hello World file
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: My first action test
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        USER_NAME: "anubhav6663"
        PASSWORD: "Te%4012291"
        MY_NAME: "anubhav"
